# Pythonイメージの取得
FROM python:3.8.6-slim-buster
# ワーキングディレクトリの指定
WORKDIR /usr/local/app
# モジュールを揃える
COPY requirements_worker.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
WORKDIR /api/worker
# 起動環境設定
ENTRYPOINT ["rqworker"]
CMD [ "--url", "redis://gcir_redis" ]